# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

base:
  outputs:

    dev:
      type: duckdb

  target: dev

postcard_company:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_FILE_PATH') }}"
      schema: postcard_company