models:
  - name: dim_channel
    config:
      contract:
        enforced: true
    columns:
      - name: channel_key
        data_type: INTEGER
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: channel_name
        data_type: VARCHAR
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['in-store', 'web', 'mobile app']
      - name: original_channel_id
        data_type: INTEGER
  - name: fact_sales
    config:
      contract:
        enforced: true
    columns:
      - name: sales_key
        data_type: VARCHAR
        tests:
          - unique
          - not_null
      - name: channel_key
        data_type: INTEGER
        tests:
          - not_null
          - relationships:
              to: ref('dim_channel')
              field: channel_key
      - name: bought_date_key
        data_type: INTEGER
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: commissionpaid
        data_type: DOUBLE
      - name: commissionpct
        data_type: DOUBLE
      - name: customer_key
        data_type: VARCHAR
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: geography_key
        data_type: INTEGER
        tests:
          - not_null
          - relationships:
              to: ref('dim_geography')
              field: geography_key
      - name: product_key
        data_type: VARCHAR
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: product_price
        data_type: DOUBLE
      - name: qty
        data_type: INTEGER
        tests:
          - not_null
      - name: total_amount
        data_type: DOUBLE
        tests:
          - not_null
      - name: transaction_id
        data_type: BIGINT
      - name: sales_agent_key
        data_type: INTEGER
        tests:
          - relationships:
              to: ref('dim_sales_agent')
              field: sales_agent_key
  - name: dim_sales_agent
    config:
      contract:
        enforced: true
      constraints:
        - type: primary_key
          columns: ["sales_agent_key"]
    columns:
      - name: sales_agent_key
        data_type: INTEGER
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: reseller_name
        data_type: VARCHAR
      - name: original_reseller_id
        data_type: INTEGER
      - name: commission_pct
        data_type: DOUBLE
  - name: dim_customer
    config:
      contract:
        enforced: true
    columns:
      - name: customer_key
        data_type: VARCHAR
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: original_customer_id
        data_type: BIGINT
      - name: customer_first_name
        data_type: VARCHAR
      - name: customer_last_name
        data_type: VARCHAR
      - name: customer_email
        data_type: VARCHAR
        tests:
          - not_null
      - name: customer_phone
        data_type: VARCHAR
      - name: customer_address
        data_type: VARCHAR
      - name: customer_city
        data_type: VARCHAR
      - name: customer_country
        data_type: VARCHAR
      - name: customer_postal_code
        data_type: VARCHAR
      - name: sales_agent_key
        data_type: INTEGER
  - name: dim_geography
    config:
      contract:
        enforced: true
    columns:
      - name: geography_key
        data_type: INTEGER
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: country_name
        data_type: VARCHAR
      - name: city_name
        data_type: VARCHAR
      - name: region_name
        data_type: VARCHAR
  - name: dim_product
    config:
      contract:
        enforced: true
    columns:
      - name: product_key
        data_type: VARCHAR
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: product_name
        data_type: VARCHAR
      - name: geography_key
        data_type: INTEGER
      - name: original_product_id
        data_type: VARCHAR
      - name: product_price
        data_type: DOUBLE
        tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"
  - name: dim_date
    config:
      contract:
        enforced: true
    columns:
      - name: date_key
        data_type: INTEGER
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: date_value
        data_type: DATE
        tests:
          - unique
          - not_null
      - name: day_of_year
        data_type: BIGINT
      - name: week_key
        data_type: BIGINT
      - name: week_of_year
        data_type: BIGINT
      - name: day_of_week
        data_type: BIGINT
      - name: iso_day_of_week
        data_type: BIGINT
      - name: day_name
        data_type: VARCHAR
      - name: first_day_of_week
        data_type: DATE
      - name: last_day_of_week
        data_type: DATE
      - name: month_key
        data_type: VARCHAR
      - name: month_of_year
        data_type: BIGINT
      - name: day_of_month
        data_type: BIGINT
      - name: month_name_short
        data_type: VARCHAR
      - name: month_name
        data_type: VARCHAR
      - name: first_day_of_month
        data_type: DATE
      - name: last_day_of_month
        data_type: DATE
      - name: quarter_key
        data_type: INTEGER
      - name: quarter_of_year
        data_type: BIGINT
      - name: day_of_quarter
        data_type: INTEGER
      - name: quarter_desc_short
        data_type: VARCHAR
      - name: quarter_desc
        data_type: VARCHAR
      - name: first_day_of_quarter
        data_type: DATE
      - name: last_day_of_quarter
        data_type: DATE
      - name: year_key
        data_type: INTEGER
      - name: first_day_of_year
        data_type: DATE
      - name: last_day_of_year
        data_type: TIMESTAMP
      - name: ordinal_weekday_of_month
        data_type: BIGINT
