models:
  - name: dim_channel
    config:
      contract:
        enforced: true  
    columns:
      - name: channel_key
        data_type: INTEGER
        constraints:
          - type: primary_key
      - name: channel_name
        data_type: VARCHAR
      - name: original_channel_id
        data_type: INTEGER
  - name: fact_sales
    config:
      contract:
        enforced: true
    columns:
      - name: channel_key
        data_type: INTEGER
      - name: bought_date_key
        data_type: INTEGER
      - name: commissionpaid
        data_type: DOUBLE 
      - name: commissionpct
        data_type: DOUBLE  
      - name: customer_key
        data_type: VARCHAR   
      - name: geography_key
        data_type: INTEGER  
      - name: product_key
        data_type: VARCHAR    
      - name: product_price
        data_type: DOUBLE  
      - name: qty
        data_type: INTEGER            
      - name: total_amount
        data_type: DOUBLE   
      - name: transaction_id
        data_type: BIGINT
  - name: dim_sales_agent
    config:
      contract:
        enforced: true
      constraints:
        - type: primary_key
          columns: ['sales_agent_key']
    columns:
      - name: sales_agent_key
        data_type: INTEGER
        constraints:
          - type: primary_key
      - name: reseller_name
        data_type: VARCHAR
      - name: original_reseller_id
        data_type: INTEGER
      - name: commission_pct
        data_type: DOUBLE
  - name: dim_customer
    config:
      contract:
        enforced: true  
    columns:
      - name: customer_key
        data_type: VARCHAR
        constraints:
          - type: primary_key
      - name: original_customer_id
        data_type: BIGINT
      - name: customer_first_name
        data_type: VARCHAR
      - name: customer_last_name
        data_type: VARCHAR
      - name: customer_email
        data_type: VARCHAR
      - name: sales_agent_key
        data_type: INTEGER
  - name: dim_geography
    config:
      contract:
        enforced: true  
    columns:
      - name: geography_key
        data_type: INTEGER
        constraints:
          - type: primary_key
      - name: country_name
        data_type: VARCHAR
      - name: city_name
        data_type: VARCHAR
      - name: region_name
        data_type: VARCHAR 
  - name: dim_product
    config:
      contract:
        enforced: true  
    columns:
      - name: product_key
        data_type: VARCHAR
        constraints:
          - type: primary_key
      - name: product_name
        data_type: VARCHAR
      - name: geography_key
        data_type: INTEGER
      - name: original_product_id
        data_type: VARCHAR
      - name: product_price
        data_type: DOUBLE